### Issue a new bill
POST {{host}}/bill/issue
Content-Type: application/json
Accept: application/json

{
  "type": 0,
  "country_of_issuing": "AT",
  "city_of_issuing": "Vienna",
  "issue_date": "2025-01-22",
  "maturity_date": "2025-06-22",
  "payee": "12D3KooWBN48JhNXAKhKxbUVM1YXRrHTfPYxjWiGpcKYGuR77cy3",
  "payer": "12D3BooWBN48JhNXAKhKxbUVM1YXRrHTfPYxjWiGpcKYGuR77555",
  "sum": "5000",
  "currency": "BTC",
  "country_of_payment": "UK",
  "city_of_payment": "London",
  "language": "en-UK"
}

