### Issue a new bill
POST {{host}}/bill/issue
Content-Type: application/json
Accept: application/json

{
  "type": 0,
  "country_of_issuing": "AT",
  "city_of_issuing": "Vienna",
  "issue_date": "2025-02-22",
  "maturity_date": "2025-06-22",
  "payee": "039180c169e5f6d7c579cf1cefa37bffd47a2b389c8125601f4068c87bea795943",
  "payer": "02c0b2884fb510672feceacdb3678b30b157b017bcb06a9fd44642aae18b522aaf",
  "drawee": "02c0b2884fb510672feceacdb3678b30b157b017bcb06a9fd44642aae18b522aaf",
  "sum": "50000",
  "currency": "SATS",
  "country_of_payment": "UK",
  "city_of_payment": "London",
  "language": "en-UK"
}

### Get Bills
GET {{host}}/bill/list
Accept: application/json

### Get Bill
GET {{host}}/bill/1
Accept: application/json

### Get Bills light
GET {{host}}/bill/list/light
Accept: application/json

### Bill search
POST {{host}}/bill/search
Content-Type: application/json
Accept: application/json
