### Create identity
POST {{host}}/identity/create
Content-Type: application/json
Accept: application/json

{
  "name": "JohnDev",
  "company": "Some Company",
  "date_of_birth": "09/23/1990",
  "city_of_birth": "Vienna",
  "country_of_birth": "Austria",
  "email": "test@example.com",
  "country": "AT",
  "city": "Vienna",
  "zip": "1020",
  "address": "Smithstreet 15, Top 22"
}

### Get identity
GET {{host}}/identity/return
Accept: application/json

### Get node id
GET {{host}}/identity/peer_id/return

### Update identity
PUT {{host}}/identity/change
Content-Type: application/json
Accept: application/json

{
  "name": "John Doe",
  "company": "Some Company",
  "email": "test@example.com",
  "country": "AT",
  "city": "Vienna",
  "zip": "1020",
  "address": "Smithstreet 15, Top 22"
}
